[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "fiap-fase3-ml-finance"
version = "0.1.0"
description = "Serverless low-cost finance ML demo (FastAPI + yfinance + AWS)"
authors = [{name="Victor"}]
dependencies = []
